name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get module version
        id: read_json
        run: |
          VERSION=$(jq -r '.version' module.json)
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

      - name: Create assets
        uses: vimtor/action-zip@v1.3
        with:
          files: |
            assets/
            lang/
            packs/
            module.json
            LICENSE
            README.md
          dest: module.zip

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.read_json.outputs.version }}
          generate_release_notes: true
          files: |
            module.zip
            module.json
